name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  macos13_test:
    name: Test
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: set -o pipefail && xcodebuild -scheme XCLint-Package -destination "platform=macOS" test | xcbeautify

  macos14_test:
    name: Test macOS 14
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: set -o pipefail && xcodebuild -scheme XCLint-Package -destination "platform=macOS" test | xcbeautify

  linux_test:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install swiftly
        run: curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash -s -- -y
      - name: Install the latest Swift toolchain
        run: swiftly install latest
      - name: Test
        run: swift test
